baseURL: https://cuentos.netlify.app
languageCode: es-ES
title: Cuentos
theme: "PaperMod"

params:
    DateFormat: "2006-01-02"
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowShareButtons: true
    ShareButtons: ["twitter", "facebook", "whatsapp", "telegram"]
    socialIcons:
        - name: "other"
          url: "https://links.jorgesanz.net"
        - name: "twitter"
          url: "https://twitter.com/xurxosanz"
        - name: "github"
          url: "https://github.com/jsanz/cuentos"
    homeInfoParams:
        Title: Cuentos para dormir 😴
        Content: >
                Algunos cuentos cortos recopilados por
                <a href="https://jorgesanz.net">Jorge Sanz</a>