baseURL: https://cuentos.netlify.app
languageCode: es-ES
title: Cuentos
theme: "PaperMod"

params:
    ShowReadingTime: true
    homeInfoParams:
        Title: Cuentos
        Content: Unos cuentos para dormir