baseURL: http://example.org/
languageCode: en-us
title: Cuentos
theme: "PaperMod"

params:
    ShowReadingTime: true
    homeInfoParams:
        Title: Cuentos
        Content: Unos cuentos para dormir